---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: composer-pvc
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/composer-pvc"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: composer-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
